// flow-typed signature: e8d4a7ee1ea383d66cebd89b73661efd
// flow-typed version: <<STUB>>/amazon-cognito-identity-js_v^1.16.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amazon-cognito-identity-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amazon-cognito-identity-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amazon-cognito-identity-js/dist/amazon-cognito-identity.min' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk.min' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/enhance' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/config' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/main' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/examples/babel-webpack/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/AuthenticationDetails' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/AuthenticationHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/BigInteger' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/CognitoAccessToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/CognitoIdToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/CognitoRefreshToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/CognitoUser' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/CognitoUserAttribute' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/CognitoUserPool' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/CognitoUserSession' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/DateHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/index' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/src/StorageHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-identity-js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/dist/amazon-cognito-identity.min'>;
}
declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/dist/aws-cognito-sdk'>;
}
declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk.min.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/dist/aws-cognito-sdk.min'>;
}
declare module 'amazon-cognito-identity-js/enhance.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/enhance'>;
}
declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/config.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/examples/babel-webpack/src/config'>;
}
declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/main.jsx' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/examples/babel-webpack/src/main'>;
}
declare module 'amazon-cognito-identity-js/examples/babel-webpack/webpack.config.babel.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/examples/babel-webpack/webpack.config.babel'>;
}
declare module 'amazon-cognito-identity-js/src/AuthenticationDetails.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/AuthenticationDetails'>;
}
declare module 'amazon-cognito-identity-js/src/AuthenticationHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/AuthenticationHelper'>;
}
declare module 'amazon-cognito-identity-js/src/BigInteger.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/BigInteger'>;
}
declare module 'amazon-cognito-identity-js/src/CognitoAccessToken.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/CognitoAccessToken'>;
}
declare module 'amazon-cognito-identity-js/src/CognitoIdToken.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/CognitoIdToken'>;
}
declare module 'amazon-cognito-identity-js/src/CognitoRefreshToken.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/CognitoRefreshToken'>;
}
declare module 'amazon-cognito-identity-js/src/CognitoUser.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/CognitoUser'>;
}
declare module 'amazon-cognito-identity-js/src/CognitoUserAttribute.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/CognitoUserAttribute'>;
}
declare module 'amazon-cognito-identity-js/src/CognitoUserPool.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/CognitoUserPool'>;
}
declare module 'amazon-cognito-identity-js/src/CognitoUserSession.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/CognitoUserSession'>;
}
declare module 'amazon-cognito-identity-js/src/DateHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/DateHelper'>;
}
declare module 'amazon-cognito-identity-js/src/index.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/index'>;
}
declare module 'amazon-cognito-identity-js/src/StorageHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/src/StorageHelper'>;
}
declare module 'amazon-cognito-identity-js/webpack.config.js' {
  declare module.exports: $Exports<'amazon-cognito-identity-js/webpack.config'>;
}
