// flow-typed signature: ac9584891312f68e1cc3f68dc8cda86d
// flow-typed version: <<STUB>>/base64-url_v^1.3.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'base64-url/index' {
  declare module.exports: $Exports<'base64-url'>;
}
declare module 'base64-url/index.js' {
  declare module.exports: $Exports<'base64-url'>;
}
