// flow-typed signature: 40abe4f0444812efa3ad3feb59e77f90
// flow-typed version: <<STUB>>/check-types_v^7.1.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'check-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'check-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'check-types/src/check-types' {
  declare module.exports: any;
}

declare module 'check-types/src/check-types.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'check-types/src/check-types.js' {
  declare module.exports: $Exports<'check-types/src/check-types'>;
}
declare module 'check-types/src/check-types.min.js' {
  declare module.exports: $Exports<'check-types/src/check-types.min'>;
}
