// flow-typed signature: e54a6196f04395c10295e8220a49cb03
// flow-typed version: <<STUB>>/csstips_v^0.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csstips'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csstips' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csstips/lib/box' {
  declare module.exports: any;
}

declare module 'csstips/lib/display' {
  declare module.exports: any;
}

declare module 'csstips/lib/flex' {
  declare module.exports: any;
}

declare module 'csstips/lib/font' {
  declare module.exports: any;
}

declare module 'csstips/lib/index' {
  declare module.exports: any;
}

declare module 'csstips/lib/layer' {
  declare module.exports: any;
}

declare module 'csstips/lib/normalize' {
  declare module.exports: any;
}

declare module 'csstips/lib/page' {
  declare module.exports: any;
}

declare module 'csstips/lib/scroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csstips/lib/box.js' {
  declare module.exports: $Exports<'csstips/lib/box'>;
}
declare module 'csstips/lib/display.js' {
  declare module.exports: $Exports<'csstips/lib/display'>;
}
declare module 'csstips/lib/flex.js' {
  declare module.exports: $Exports<'csstips/lib/flex'>;
}
declare module 'csstips/lib/font.js' {
  declare module.exports: $Exports<'csstips/lib/font'>;
}
declare module 'csstips/lib/index.js' {
  declare module.exports: $Exports<'csstips/lib/index'>;
}
declare module 'csstips/lib/layer.js' {
  declare module.exports: $Exports<'csstips/lib/layer'>;
}
declare module 'csstips/lib/normalize.js' {
  declare module.exports: $Exports<'csstips/lib/normalize'>;
}
declare module 'csstips/lib/page.js' {
  declare module.exports: $Exports<'csstips/lib/page'>;
}
declare module 'csstips/lib/scroll.js' {
  declare module.exports: $Exports<'csstips/lib/scroll'>;
}
