// flow-typed signature: bc63a151ba27c30d14c5f0611d09f109
// flow-typed version: <<STUB>>/csx_v^8.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csx/lib/background' {
  declare module.exports: any;
}

declare module 'csx/lib/color' {
  declare module.exports: any;
}

declare module 'csx/lib/general' {
  declare module.exports: any;
}

declare module 'csx/lib/gradient' {
  declare module.exports: any;
}

declare module 'csx/lib/index' {
  declare module.exports: any;
}

declare module 'csx/lib/interfaces' {
  declare module.exports: any;
}

declare module 'csx/lib/internal/formatting' {
  declare module.exports: any;
}

declare module 'csx/lib/lists' {
  declare module.exports: any;
}

declare module 'csx/lib/strings' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/background' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/color' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/gradient' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/lists' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/strings' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/transforms' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/units' {
  declare module.exports: any;
}

declare module 'csx/lib/tests/utils' {
  declare module.exports: any;
}

declare module 'csx/lib/transform' {
  declare module.exports: any;
}

declare module 'csx/lib/transforms' {
  declare module.exports: any;
}

declare module 'csx/lib/types' {
  declare module.exports: any;
}

declare module 'csx/lib/units' {
  declare module.exports: any;
}

declare module 'csx/lib/utils/formatting' {
  declare module.exports: any;
}

declare module 'csx/umd/csx' {
  declare module.exports: any;
}

declare module 'csx/umd/csx.min' {
  declare module.exports: any;
}

declare module 'csx/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csx/lib/background.js' {
  declare module.exports: $Exports<'csx/lib/background'>;
}
declare module 'csx/lib/color.js' {
  declare module.exports: $Exports<'csx/lib/color'>;
}
declare module 'csx/lib/general.js' {
  declare module.exports: $Exports<'csx/lib/general'>;
}
declare module 'csx/lib/gradient.js' {
  declare module.exports: $Exports<'csx/lib/gradient'>;
}
declare module 'csx/lib/index.js' {
  declare module.exports: $Exports<'csx/lib/index'>;
}
declare module 'csx/lib/interfaces.js' {
  declare module.exports: $Exports<'csx/lib/interfaces'>;
}
declare module 'csx/lib/internal/formatting.js' {
  declare module.exports: $Exports<'csx/lib/internal/formatting'>;
}
declare module 'csx/lib/lists.js' {
  declare module.exports: $Exports<'csx/lib/lists'>;
}
declare module 'csx/lib/strings.js' {
  declare module.exports: $Exports<'csx/lib/strings'>;
}
declare module 'csx/lib/tests/background.js' {
  declare module.exports: $Exports<'csx/lib/tests/background'>;
}
declare module 'csx/lib/tests/color.js' {
  declare module.exports: $Exports<'csx/lib/tests/color'>;
}
declare module 'csx/lib/tests/gradient.js' {
  declare module.exports: $Exports<'csx/lib/tests/gradient'>;
}
declare module 'csx/lib/tests/lists.js' {
  declare module.exports: $Exports<'csx/lib/tests/lists'>;
}
declare module 'csx/lib/tests/strings.js' {
  declare module.exports: $Exports<'csx/lib/tests/strings'>;
}
declare module 'csx/lib/tests/transforms.js' {
  declare module.exports: $Exports<'csx/lib/tests/transforms'>;
}
declare module 'csx/lib/tests/units.js' {
  declare module.exports: $Exports<'csx/lib/tests/units'>;
}
declare module 'csx/lib/tests/utils.js' {
  declare module.exports: $Exports<'csx/lib/tests/utils'>;
}
declare module 'csx/lib/transform.js' {
  declare module.exports: $Exports<'csx/lib/transform'>;
}
declare module 'csx/lib/transforms.js' {
  declare module.exports: $Exports<'csx/lib/transforms'>;
}
declare module 'csx/lib/types.js' {
  declare module.exports: $Exports<'csx/lib/types'>;
}
declare module 'csx/lib/units.js' {
  declare module.exports: $Exports<'csx/lib/units'>;
}
declare module 'csx/lib/utils/formatting.js' {
  declare module.exports: $Exports<'csx/lib/utils/formatting'>;
}
declare module 'csx/umd/csx.js' {
  declare module.exports: $Exports<'csx/umd/csx'>;
}
declare module 'csx/umd/csx.min.js' {
  declare module.exports: $Exports<'csx/umd/csx.min'>;
}
declare module 'csx/webpack.config.js' {
  declare module.exports: $Exports<'csx/webpack.config'>;
}
