// flow-typed signature: 1934a8be2cbeae71ff6daec08c954c2f
// flow-typed version: <<STUB>>/firebase_v^4.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase/app' {
  declare module.exports: any;
}

declare module 'firebase/app/deep_copy' {
  declare module.exports: any;
}

declare module 'firebase/app/errors' {
  declare module.exports: any;
}

declare module 'firebase/app/firebase_app' {
  declare module.exports: any;
}

declare module 'firebase/app/shared_promise' {
  declare module.exports: any;
}

declare module 'firebase/app/subscribe' {
  declare module.exports: any;
}

declare module 'firebase/auth' {
  declare module.exports: any;
}

declare module 'firebase/database-node' {
  declare module.exports: any;
}

declare module 'firebase/database' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-app-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-app-internal-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-client-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-database-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-database-internal-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-error-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-messaging-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-storage-externs' {
  declare module.exports: any;
}

declare module 'firebase/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase/firebase-auth' {
  declare module.exports: any;
}

declare module 'firebase/firebase-browser' {
  declare module.exports: any;
}

declare module 'firebase/firebase-database' {
  declare module.exports: any;
}

declare module 'firebase/firebase-messaging' {
  declare module.exports: any;
}

declare module 'firebase/firebase-node' {
  declare module.exports: any;
}

declare module 'firebase/firebase-react-native' {
  declare module.exports: any;
}

declare module 'firebase/firebase-storage' {
  declare module.exports: any;
}

declare module 'firebase/firebase' {
  declare module.exports: any;
}

declare module 'firebase/messaging' {
  declare module.exports: any;
}

declare module 'firebase/messaging/controllers/controller-interface' {
  declare module.exports: any;
}

declare module 'firebase/messaging/controllers/sw-controller' {
  declare module.exports: any;
}

declare module 'firebase/messaging/controllers/window-controller' {
  declare module.exports: any;
}

declare module 'firebase/messaging/helpers/array-buffer-to-base64' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/db-interface' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/default-sw' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/errors' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/fcm-details' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/notification-permission' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/token-details-model' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/token-manager' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/vapid-details-model' {
  declare module.exports: any;
}

declare module 'firebase/messaging/models/worker-page-message' {
  declare module.exports: any;
}

declare module 'firebase/storage' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/args' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/array' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/async' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/authwrapper' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/backoff' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/blob' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/constants' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/error' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/failrequest' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/fs' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/json' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/location' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/metadata' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/object' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/observer' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/path' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/promise_external' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/request' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/requestinfo' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/requestmaker' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/requestmap' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/requests' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/string' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/taskenums' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/type' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/url' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/xhrio_network' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/xhrio' {
  declare module.exports: any;
}

declare module 'firebase/storage/implementation/xhriopool' {
  declare module.exports: any;
}

declare module 'firebase/storage/metadata' {
  declare module.exports: any;
}

declare module 'firebase/storage/reference' {
  declare module.exports: any;
}

declare module 'firebase/storage/service' {
  declare module.exports: any;
}

declare module 'firebase/storage/task' {
  declare module.exports: any;
}

declare module 'firebase/storage/tasksnapshot' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/app.js' {
  declare module.exports: $Exports<'firebase/app'>;
}
declare module 'firebase/app/deep_copy.js' {
  declare module.exports: $Exports<'firebase/app/deep_copy'>;
}
declare module 'firebase/app/errors.js' {
  declare module.exports: $Exports<'firebase/app/errors'>;
}
declare module 'firebase/app/firebase_app.js' {
  declare module.exports: $Exports<'firebase/app/firebase_app'>;
}
declare module 'firebase/app/shared_promise.js' {
  declare module.exports: $Exports<'firebase/app/shared_promise'>;
}
declare module 'firebase/app/subscribe.js' {
  declare module.exports: $Exports<'firebase/app/subscribe'>;
}
declare module 'firebase/auth.js' {
  declare module.exports: $Exports<'firebase/auth'>;
}
declare module 'firebase/database-node.js' {
  declare module.exports: $Exports<'firebase/database-node'>;
}
declare module 'firebase/database.js' {
  declare module.exports: $Exports<'firebase/database'>;
}
declare module 'firebase/externs/firebase-app-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-app-externs'>;
}
declare module 'firebase/externs/firebase-app-internal-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-app-internal-externs'>;
}
declare module 'firebase/externs/firebase-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-auth-externs'>;
}
declare module 'firebase/externs/firebase-client-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-client-auth-externs'>;
}
declare module 'firebase/externs/firebase-database-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-database-externs'>;
}
declare module 'firebase/externs/firebase-database-internal-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-database-internal-externs'>;
}
declare module 'firebase/externs/firebase-error-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-error-externs'>;
}
declare module 'firebase/externs/firebase-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-externs'>;
}
declare module 'firebase/externs/firebase-messaging-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-messaging-externs'>;
}
declare module 'firebase/externs/firebase-storage-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-storage-externs'>;
}
declare module 'firebase/firebase-app.js' {
  declare module.exports: $Exports<'firebase/firebase-app'>;
}
declare module 'firebase/firebase-auth.js' {
  declare module.exports: $Exports<'firebase/firebase-auth'>;
}
declare module 'firebase/firebase-browser.js' {
  declare module.exports: $Exports<'firebase/firebase-browser'>;
}
declare module 'firebase/firebase-database.js' {
  declare module.exports: $Exports<'firebase/firebase-database'>;
}
declare module 'firebase/firebase-messaging.js' {
  declare module.exports: $Exports<'firebase/firebase-messaging'>;
}
declare module 'firebase/firebase-node.js' {
  declare module.exports: $Exports<'firebase/firebase-node'>;
}
declare module 'firebase/firebase-react-native.js' {
  declare module.exports: $Exports<'firebase/firebase-react-native'>;
}
declare module 'firebase/firebase-storage.js' {
  declare module.exports: $Exports<'firebase/firebase-storage'>;
}
declare module 'firebase/firebase.js' {
  declare module.exports: $Exports<'firebase/firebase'>;
}
declare module 'firebase/messaging.js' {
  declare module.exports: $Exports<'firebase/messaging'>;
}
declare module 'firebase/messaging/controllers/controller-interface.js' {
  declare module.exports: $Exports<'firebase/messaging/controllers/controller-interface'>;
}
declare module 'firebase/messaging/controllers/sw-controller.js' {
  declare module.exports: $Exports<'firebase/messaging/controllers/sw-controller'>;
}
declare module 'firebase/messaging/controllers/window-controller.js' {
  declare module.exports: $Exports<'firebase/messaging/controllers/window-controller'>;
}
declare module 'firebase/messaging/helpers/array-buffer-to-base64.js' {
  declare module.exports: $Exports<'firebase/messaging/helpers/array-buffer-to-base64'>;
}
declare module 'firebase/messaging/models/db-interface.js' {
  declare module.exports: $Exports<'firebase/messaging/models/db-interface'>;
}
declare module 'firebase/messaging/models/default-sw.js' {
  declare module.exports: $Exports<'firebase/messaging/models/default-sw'>;
}
declare module 'firebase/messaging/models/errors.js' {
  declare module.exports: $Exports<'firebase/messaging/models/errors'>;
}
declare module 'firebase/messaging/models/fcm-details.js' {
  declare module.exports: $Exports<'firebase/messaging/models/fcm-details'>;
}
declare module 'firebase/messaging/models/notification-permission.js' {
  declare module.exports: $Exports<'firebase/messaging/models/notification-permission'>;
}
declare module 'firebase/messaging/models/token-details-model.js' {
  declare module.exports: $Exports<'firebase/messaging/models/token-details-model'>;
}
declare module 'firebase/messaging/models/token-manager.js' {
  declare module.exports: $Exports<'firebase/messaging/models/token-manager'>;
}
declare module 'firebase/messaging/models/vapid-details-model.js' {
  declare module.exports: $Exports<'firebase/messaging/models/vapid-details-model'>;
}
declare module 'firebase/messaging/models/worker-page-message.js' {
  declare module.exports: $Exports<'firebase/messaging/models/worker-page-message'>;
}
declare module 'firebase/storage.js' {
  declare module.exports: $Exports<'firebase/storage'>;
}
declare module 'firebase/storage/implementation/args.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/args'>;
}
declare module 'firebase/storage/implementation/array.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/array'>;
}
declare module 'firebase/storage/implementation/async.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/async'>;
}
declare module 'firebase/storage/implementation/authwrapper.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/authwrapper'>;
}
declare module 'firebase/storage/implementation/backoff.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/backoff'>;
}
declare module 'firebase/storage/implementation/blob.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/blob'>;
}
declare module 'firebase/storage/implementation/constants.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/constants'>;
}
declare module 'firebase/storage/implementation/error.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/error'>;
}
declare module 'firebase/storage/implementation/failrequest.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/failrequest'>;
}
declare module 'firebase/storage/implementation/fs.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/fs'>;
}
declare module 'firebase/storage/implementation/json.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/json'>;
}
declare module 'firebase/storage/implementation/location.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/location'>;
}
declare module 'firebase/storage/implementation/metadata.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/metadata'>;
}
declare module 'firebase/storage/implementation/object.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/object'>;
}
declare module 'firebase/storage/implementation/observer.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/observer'>;
}
declare module 'firebase/storage/implementation/path.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/path'>;
}
declare module 'firebase/storage/implementation/promise_external.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/promise_external'>;
}
declare module 'firebase/storage/implementation/request.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/request'>;
}
declare module 'firebase/storage/implementation/requestinfo.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/requestinfo'>;
}
declare module 'firebase/storage/implementation/requestmaker.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/requestmaker'>;
}
declare module 'firebase/storage/implementation/requestmap.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/requestmap'>;
}
declare module 'firebase/storage/implementation/requests.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/requests'>;
}
declare module 'firebase/storage/implementation/string.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/string'>;
}
declare module 'firebase/storage/implementation/taskenums.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/taskenums'>;
}
declare module 'firebase/storage/implementation/type.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/type'>;
}
declare module 'firebase/storage/implementation/url.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/url'>;
}
declare module 'firebase/storage/implementation/xhrio_network.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/xhrio_network'>;
}
declare module 'firebase/storage/implementation/xhrio.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/xhrio'>;
}
declare module 'firebase/storage/implementation/xhriopool.js' {
  declare module.exports: $Exports<'firebase/storage/implementation/xhriopool'>;
}
declare module 'firebase/storage/metadata.js' {
  declare module.exports: $Exports<'firebase/storage/metadata'>;
}
declare module 'firebase/storage/reference.js' {
  declare module.exports: $Exports<'firebase/storage/reference'>;
}
declare module 'firebase/storage/service.js' {
  declare module.exports: $Exports<'firebase/storage/service'>;
}
declare module 'firebase/storage/task.js' {
  declare module.exports: $Exports<'firebase/storage/task'>;
}
declare module 'firebase/storage/tasksnapshot.js' {
  declare module.exports: $Exports<'firebase/storage/tasksnapshot'>;
}
