// flow-typed signature: 0467f9577cff1a1204e9f41792a8ae96
// flow-typed version: <<STUB>>/json_v^9.0.6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json/lib/json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json/lib/json.js' {
  declare module.exports: $Exports<'json/lib/json'>;
}
