// flow-typed signature: 2076a330f1576233d2f23747116eb4b3
// flow-typed version: <<STUB>>/liform-react_v^0.5.15/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'liform-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'liform-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'liform-react/dist/liform' {
  declare module.exports: any;
}

declare module 'liform-react/dist/liform.min' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/buildSyncValidation' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/createLiformSpec' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/processSubmitErrors' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/renderFields' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/setup' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/test-utils' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.ArrayWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.CheckboxWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.ChoiceWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.ColorWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.CompatibleDateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.compatibleDateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.DateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.DateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.EmailWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.FileWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.MoneyWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.NumberWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.PasswordWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.PercentWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.SearchWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.StringWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.TextareaWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.TimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/__tests__/themes.bootstrap3.UrlWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/buildSyncValidation' {
  declare module.exports: any;
}

declare module 'liform-react/lib/index' {
  declare module.exports: any;
}

declare module 'liform-react/lib/processSubmitErrors' {
  declare module.exports: any;
}

declare module 'liform-react/lib/renderField' {
  declare module.exports: any;
}

declare module 'liform-react/lib/renderFields' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/ArrayWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/BaseInputWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/CheckboxWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/ChoiceWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/ColorWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/CompatibleDateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/CompatibleDateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/DateSelector' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/DateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/DateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/EmailWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/FileWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/index' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/MoneyWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/NumberWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/ObjectWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/PasswordWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/PercentWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/SearchWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/StringWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/TextareaWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/TimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/bootstrap3/UrlWidget' {
  declare module.exports: any;
}

declare module 'liform-react/lib/themes/index' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/buildSyncValidation' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/createLiformSpec' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/processSubmitErrors' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/renderFields' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/setup' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/test-utils' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.ArrayWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.CheckboxWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.ChoiceWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.ColorWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.CompatibleDateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.CompatibleDateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.DateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.DateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.EmailWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.FileWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.MoneyWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.NumberWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.PasswordWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.PercentWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.SearchWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.StringWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.TextareaWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.TimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/__tests__/themes.bootstrap3.UrlWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/buildSyncValidation' {
  declare module.exports: any;
}

declare module 'liform-react/src/index' {
  declare module.exports: any;
}

declare module 'liform-react/src/processSubmitErrors' {
  declare module.exports: any;
}

declare module 'liform-react/src/renderField' {
  declare module.exports: any;
}

declare module 'liform-react/src/renderFields' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/ArrayWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/BaseInputWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/CheckboxWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/ChoiceWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/ColorWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/CompatibleDateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/CompatibleDateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/DateSelector' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/DateTimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/DateWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/EmailWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/FileWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/index' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/MoneyWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/NumberWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/ObjectWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/PasswordWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/PercentWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/SearchWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/StringWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/TextareaWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/TimeWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/bootstrap3/UrlWidget' {
  declare module.exports: any;
}

declare module 'liform-react/src/themes/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'liform-react/dist/liform.js' {
  declare module.exports: $Exports<'liform-react/dist/liform'>;
}
declare module 'liform-react/dist/liform.min.js' {
  declare module.exports: $Exports<'liform-react/dist/liform.min'>;
}
declare module 'liform-react/lib/__tests__/buildSyncValidation.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/buildSyncValidation'>;
}
declare module 'liform-react/lib/__tests__/createLiformSpec.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/createLiformSpec'>;
}
declare module 'liform-react/lib/__tests__/processSubmitErrors.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/processSubmitErrors'>;
}
declare module 'liform-react/lib/__tests__/renderFields.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/renderFields'>;
}
declare module 'liform-react/lib/__tests__/setup.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/setup'>;
}
declare module 'liform-react/lib/__tests__/test-utils.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/test-utils'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.ArrayWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.ArrayWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.CheckboxWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.CheckboxWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.ChoiceWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.ChoiceWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.ColorWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.ColorWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.CompatibleDateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.CompatibleDateTimeWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.compatibleDateWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.compatibleDateWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.DateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.DateTimeWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.DateWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.DateWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.EmailWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.EmailWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.FileWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.FileWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.MoneyWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.MoneyWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.NumberWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.NumberWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.PasswordWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.PasswordWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.PercentWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.PercentWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.SearchWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.SearchWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.StringWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.StringWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.TextareaWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.TextareaWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.TimeWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.TimeWidget'>;
}
declare module 'liform-react/lib/__tests__/themes.bootstrap3.UrlWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/__tests__/themes.bootstrap3.UrlWidget'>;
}
declare module 'liform-react/lib/buildSyncValidation.js' {
  declare module.exports: $Exports<'liform-react/lib/buildSyncValidation'>;
}
declare module 'liform-react/lib/index.js' {
  declare module.exports: $Exports<'liform-react/lib/index'>;
}
declare module 'liform-react/lib/processSubmitErrors.js' {
  declare module.exports: $Exports<'liform-react/lib/processSubmitErrors'>;
}
declare module 'liform-react/lib/renderField.js' {
  declare module.exports: $Exports<'liform-react/lib/renderField'>;
}
declare module 'liform-react/lib/renderFields.js' {
  declare module.exports: $Exports<'liform-react/lib/renderFields'>;
}
declare module 'liform-react/lib/themes/bootstrap3/ArrayWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/ArrayWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/BaseInputWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/BaseInputWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/CheckboxWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/CheckboxWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/ChoiceWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/ChoiceWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/ColorWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/ColorWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/CompatibleDateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/CompatibleDateTimeWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/CompatibleDateWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/CompatibleDateWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/DateSelector.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/DateSelector'>;
}
declare module 'liform-react/lib/themes/bootstrap3/DateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/DateTimeWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/DateWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/DateWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/EmailWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/EmailWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/FileWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/FileWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/index.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/index'>;
}
declare module 'liform-react/lib/themes/bootstrap3/MoneyWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/MoneyWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/NumberWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/NumberWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/ObjectWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/ObjectWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/PasswordWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/PasswordWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/PercentWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/PercentWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/SearchWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/SearchWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/StringWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/StringWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/TextareaWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/TextareaWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/TimeWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/TimeWidget'>;
}
declare module 'liform-react/lib/themes/bootstrap3/UrlWidget.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/bootstrap3/UrlWidget'>;
}
declare module 'liform-react/lib/themes/index.js' {
  declare module.exports: $Exports<'liform-react/lib/themes/index'>;
}
declare module 'liform-react/src/__tests__/buildSyncValidation.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/buildSyncValidation'>;
}
declare module 'liform-react/src/__tests__/createLiformSpec.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/createLiformSpec'>;
}
declare module 'liform-react/src/__tests__/processSubmitErrors.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/processSubmitErrors'>;
}
declare module 'liform-react/src/__tests__/renderFields.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/renderFields'>;
}
declare module 'liform-react/src/__tests__/setup.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/setup'>;
}
declare module 'liform-react/src/__tests__/test-utils.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/test-utils'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.ArrayWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.ArrayWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.CheckboxWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.CheckboxWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.ChoiceWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.ChoiceWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.ColorWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.ColorWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.CompatibleDateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.CompatibleDateTimeWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.CompatibleDateWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.CompatibleDateWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.DateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.DateTimeWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.DateWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.DateWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.EmailWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.EmailWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.FileWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.FileWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.MoneyWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.MoneyWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.NumberWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.NumberWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.PasswordWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.PasswordWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.PercentWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.PercentWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.SearchWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.SearchWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.StringWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.StringWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.TextareaWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.TextareaWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.TimeWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.TimeWidget'>;
}
declare module 'liform-react/src/__tests__/themes.bootstrap3.UrlWidget.js' {
  declare module.exports: $Exports<'liform-react/src/__tests__/themes.bootstrap3.UrlWidget'>;
}
declare module 'liform-react/src/buildSyncValidation.js' {
  declare module.exports: $Exports<'liform-react/src/buildSyncValidation'>;
}
declare module 'liform-react/src/index.js' {
  declare module.exports: $Exports<'liform-react/src/index'>;
}
declare module 'liform-react/src/processSubmitErrors.js' {
  declare module.exports: $Exports<'liform-react/src/processSubmitErrors'>;
}
declare module 'liform-react/src/renderField.js' {
  declare module.exports: $Exports<'liform-react/src/renderField'>;
}
declare module 'liform-react/src/renderFields.js' {
  declare module.exports: $Exports<'liform-react/src/renderFields'>;
}
declare module 'liform-react/src/themes/bootstrap3/ArrayWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/ArrayWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/BaseInputWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/BaseInputWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/CheckboxWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/CheckboxWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/ChoiceWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/ChoiceWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/ColorWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/ColorWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/CompatibleDateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/CompatibleDateTimeWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/CompatibleDateWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/CompatibleDateWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/DateSelector.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/DateSelector'>;
}
declare module 'liform-react/src/themes/bootstrap3/DateTimeWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/DateTimeWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/DateWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/DateWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/EmailWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/EmailWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/FileWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/FileWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/index.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/index'>;
}
declare module 'liform-react/src/themes/bootstrap3/MoneyWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/MoneyWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/NumberWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/NumberWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/ObjectWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/ObjectWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/PasswordWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/PasswordWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/PercentWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/PercentWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/SearchWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/SearchWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/StringWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/StringWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/TextareaWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/TextareaWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/TimeWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/TimeWidget'>;
}
declare module 'liform-react/src/themes/bootstrap3/UrlWidget.js' {
  declare module.exports: $Exports<'liform-react/src/themes/bootstrap3/UrlWidget'>;
}
declare module 'liform-react/src/themes/index.js' {
  declare module.exports: $Exports<'liform-react/src/themes/index'>;
}
