// flow-typed signature: 08cde9012ddab36887e9008016581ca1
// flow-typed version: <<STUB>>/rdf-store-inmemory_v^0.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rdf-store-inmemory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rdf-store-inmemory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rdf-store-inmemory/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rdf-store-inmemory/index' {
  declare module.exports: $Exports<'rdf-store-inmemory'>;
}
declare module 'rdf-store-inmemory/index.js' {
  declare module.exports: $Exports<'rdf-store-inmemory'>;
}
declare module 'rdf-store-inmemory/test/test.js' {
  declare module.exports: $Exports<'rdf-store-inmemory/test/test'>;
}
