// flow-typed signature: bdfa42072f3d5c954997c2a9e950c492
// flow-typed version: <<STUB>>/rdflib_v^0.14.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rdflib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rdflib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rdflib/dist/rdflib' {
  declare module.exports: any;
}

declare module 'rdflib/dist/rdflib.min' {
  declare module.exports: any;
}

declare module 'rdflib/lib/blank-node' {
  declare module.exports: any;
}

declare module 'rdflib/lib/class-order' {
  declare module.exports: any;
}

declare module 'rdflib/lib/collection' {
  declare module.exports: any;
}

declare module 'rdflib/lib/convert' {
  declare module.exports: any;
}

declare module 'rdflib/lib/data-factory' {
  declare module.exports: any;
}

declare module 'rdflib/lib/default-graph' {
  declare module.exports: any;
}

declare module 'rdflib/lib/empty' {
  declare module.exports: any;
}

declare module 'rdflib/lib/fetcher' {
  declare module.exports: any;
}

declare module 'rdflib/lib/formula' {
  declare module.exports: any;
}

declare module 'rdflib/lib/index' {
  declare module.exports: any;
}

declare module 'rdflib/lib/indexed-formula' {
  declare module.exports: any;
}

declare module 'rdflib/lib/jsonparser' {
  declare module.exports: any;
}

declare module 'rdflib/lib/literal' {
  declare module.exports: any;
}

declare module 'rdflib/lib/log' {
  declare module.exports: any;
}

declare module 'rdflib/lib/n3parser' {
  declare module.exports: any;
}

declare module 'rdflib/lib/named-node' {
  declare module.exports: any;
}

declare module 'rdflib/lib/namespace' {
  declare module.exports: any;
}

declare module 'rdflib/lib/node' {
  declare module.exports: any;
}

declare module 'rdflib/lib/parse' {
  declare module.exports: any;
}

declare module 'rdflib/lib/patch-parser' {
  declare module.exports: any;
}

declare module 'rdflib/lib/query-to-sparql' {
  declare module.exports: any;
}

declare module 'rdflib/lib/query' {
  declare module.exports: any;
}

declare module 'rdflib/lib/rdfaparser' {
  declare module.exports: any;
}

declare module 'rdflib/lib/rdfxmlparser' {
  declare module.exports: any;
}

declare module 'rdflib/lib/serialize' {
  declare module.exports: any;
}

declare module 'rdflib/lib/serializer' {
  declare module.exports: any;
}

declare module 'rdflib/lib/sparql-to-query' {
  declare module.exports: any;
}

declare module 'rdflib/lib/statement' {
  declare module.exports: any;
}

declare module 'rdflib/lib/update-manager' {
  declare module.exports: any;
}

declare module 'rdflib/lib/updates-via' {
  declare module.exports: any;
}

declare module 'rdflib/lib/uri' {
  declare module.exports: any;
}

declare module 'rdflib/lib/util' {
  declare module.exports: any;
}

declare module 'rdflib/lib/variable' {
  declare module.exports: any;
}

declare module 'rdflib/lib/xsd' {
  declare module.exports: any;
}

declare module 'rdflib/src/blank-node' {
  declare module.exports: any;
}

declare module 'rdflib/src/class-order' {
  declare module.exports: any;
}

declare module 'rdflib/src/collection' {
  declare module.exports: any;
}

declare module 'rdflib/src/convert' {
  declare module.exports: any;
}

declare module 'rdflib/src/data-factory' {
  declare module.exports: any;
}

declare module 'rdflib/src/default-graph' {
  declare module.exports: any;
}

declare module 'rdflib/src/empty' {
  declare module.exports: any;
}

declare module 'rdflib/src/fetcher' {
  declare module.exports: any;
}

declare module 'rdflib/src/formula' {
  declare module.exports: any;
}

declare module 'rdflib/src/index' {
  declare module.exports: any;
}

declare module 'rdflib/src/indexed-formula' {
  declare module.exports: any;
}

declare module 'rdflib/src/jsonparser' {
  declare module.exports: any;
}

declare module 'rdflib/src/literal' {
  declare module.exports: any;
}

declare module 'rdflib/src/log' {
  declare module.exports: any;
}

declare module 'rdflib/src/n3parser' {
  declare module.exports: any;
}

declare module 'rdflib/src/named-node' {
  declare module.exports: any;
}

declare module 'rdflib/src/namespace' {
  declare module.exports: any;
}

declare module 'rdflib/src/node' {
  declare module.exports: any;
}

declare module 'rdflib/src/parse' {
  declare module.exports: any;
}

declare module 'rdflib/src/patch-parser' {
  declare module.exports: any;
}

declare module 'rdflib/src/query-to-sparql' {
  declare module.exports: any;
}

declare module 'rdflib/src/query' {
  declare module.exports: any;
}

declare module 'rdflib/src/rdfaparser' {
  declare module.exports: any;
}

declare module 'rdflib/src/rdfxmlparser' {
  declare module.exports: any;
}

declare module 'rdflib/src/serialize' {
  declare module.exports: any;
}

declare module 'rdflib/src/serializer' {
  declare module.exports: any;
}

declare module 'rdflib/src/sparql-to-query' {
  declare module.exports: any;
}

declare module 'rdflib/src/statement' {
  declare module.exports: any;
}

declare module 'rdflib/src/update-manager' {
  declare module.exports: any;
}

declare module 'rdflib/src/updates-via' {
  declare module.exports: any;
}

declare module 'rdflib/src/uri' {
  declare module.exports: any;
}

declare module 'rdflib/src/util' {
  declare module.exports: any;
}

declare module 'rdflib/src/variable' {
  declare module.exports: any;
}

declare module 'rdflib/src/xsd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rdflib/dist/rdflib.js' {
  declare module.exports: $Exports<'rdflib/dist/rdflib'>;
}
declare module 'rdflib/dist/rdflib.min.js' {
  declare module.exports: $Exports<'rdflib/dist/rdflib.min'>;
}
declare module 'rdflib/lib/blank-node.js' {
  declare module.exports: $Exports<'rdflib/lib/blank-node'>;
}
declare module 'rdflib/lib/class-order.js' {
  declare module.exports: $Exports<'rdflib/lib/class-order'>;
}
declare module 'rdflib/lib/collection.js' {
  declare module.exports: $Exports<'rdflib/lib/collection'>;
}
declare module 'rdflib/lib/convert.js' {
  declare module.exports: $Exports<'rdflib/lib/convert'>;
}
declare module 'rdflib/lib/data-factory.js' {
  declare module.exports: $Exports<'rdflib/lib/data-factory'>;
}
declare module 'rdflib/lib/default-graph.js' {
  declare module.exports: $Exports<'rdflib/lib/default-graph'>;
}
declare module 'rdflib/lib/empty.js' {
  declare module.exports: $Exports<'rdflib/lib/empty'>;
}
declare module 'rdflib/lib/fetcher.js' {
  declare module.exports: $Exports<'rdflib/lib/fetcher'>;
}
declare module 'rdflib/lib/formula.js' {
  declare module.exports: $Exports<'rdflib/lib/formula'>;
}
declare module 'rdflib/lib/index.js' {
  declare module.exports: $Exports<'rdflib/lib/index'>;
}
declare module 'rdflib/lib/indexed-formula.js' {
  declare module.exports: $Exports<'rdflib/lib/indexed-formula'>;
}
declare module 'rdflib/lib/jsonparser.js' {
  declare module.exports: $Exports<'rdflib/lib/jsonparser'>;
}
declare module 'rdflib/lib/literal.js' {
  declare module.exports: $Exports<'rdflib/lib/literal'>;
}
declare module 'rdflib/lib/log.js' {
  declare module.exports: $Exports<'rdflib/lib/log'>;
}
declare module 'rdflib/lib/n3parser.js' {
  declare module.exports: $Exports<'rdflib/lib/n3parser'>;
}
declare module 'rdflib/lib/named-node.js' {
  declare module.exports: $Exports<'rdflib/lib/named-node'>;
}
declare module 'rdflib/lib/namespace.js' {
  declare module.exports: $Exports<'rdflib/lib/namespace'>;
}
declare module 'rdflib/lib/node.js' {
  declare module.exports: $Exports<'rdflib/lib/node'>;
}
declare module 'rdflib/lib/parse.js' {
  declare module.exports: $Exports<'rdflib/lib/parse'>;
}
declare module 'rdflib/lib/patch-parser.js' {
  declare module.exports: $Exports<'rdflib/lib/patch-parser'>;
}
declare module 'rdflib/lib/query-to-sparql.js' {
  declare module.exports: $Exports<'rdflib/lib/query-to-sparql'>;
}
declare module 'rdflib/lib/query.js' {
  declare module.exports: $Exports<'rdflib/lib/query'>;
}
declare module 'rdflib/lib/rdfaparser.js' {
  declare module.exports: $Exports<'rdflib/lib/rdfaparser'>;
}
declare module 'rdflib/lib/rdfxmlparser.js' {
  declare module.exports: $Exports<'rdflib/lib/rdfxmlparser'>;
}
declare module 'rdflib/lib/serialize.js' {
  declare module.exports: $Exports<'rdflib/lib/serialize'>;
}
declare module 'rdflib/lib/serializer.js' {
  declare module.exports: $Exports<'rdflib/lib/serializer'>;
}
declare module 'rdflib/lib/sparql-to-query.js' {
  declare module.exports: $Exports<'rdflib/lib/sparql-to-query'>;
}
declare module 'rdflib/lib/statement.js' {
  declare module.exports: $Exports<'rdflib/lib/statement'>;
}
declare module 'rdflib/lib/update-manager.js' {
  declare module.exports: $Exports<'rdflib/lib/update-manager'>;
}
declare module 'rdflib/lib/updates-via.js' {
  declare module.exports: $Exports<'rdflib/lib/updates-via'>;
}
declare module 'rdflib/lib/uri.js' {
  declare module.exports: $Exports<'rdflib/lib/uri'>;
}
declare module 'rdflib/lib/util.js' {
  declare module.exports: $Exports<'rdflib/lib/util'>;
}
declare module 'rdflib/lib/variable.js' {
  declare module.exports: $Exports<'rdflib/lib/variable'>;
}
declare module 'rdflib/lib/xsd.js' {
  declare module.exports: $Exports<'rdflib/lib/xsd'>;
}
declare module 'rdflib/src/blank-node.js' {
  declare module.exports: $Exports<'rdflib/src/blank-node'>;
}
declare module 'rdflib/src/class-order.js' {
  declare module.exports: $Exports<'rdflib/src/class-order'>;
}
declare module 'rdflib/src/collection.js' {
  declare module.exports: $Exports<'rdflib/src/collection'>;
}
declare module 'rdflib/src/convert.js' {
  declare module.exports: $Exports<'rdflib/src/convert'>;
}
declare module 'rdflib/src/data-factory.js' {
  declare module.exports: $Exports<'rdflib/src/data-factory'>;
}
declare module 'rdflib/src/default-graph.js' {
  declare module.exports: $Exports<'rdflib/src/default-graph'>;
}
declare module 'rdflib/src/empty.js' {
  declare module.exports: $Exports<'rdflib/src/empty'>;
}
declare module 'rdflib/src/fetcher.js' {
  declare module.exports: $Exports<'rdflib/src/fetcher'>;
}
declare module 'rdflib/src/formula.js' {
  declare module.exports: $Exports<'rdflib/src/formula'>;
}
declare module 'rdflib/src/index.js' {
  declare module.exports: $Exports<'rdflib/src/index'>;
}
declare module 'rdflib/src/indexed-formula.js' {
  declare module.exports: $Exports<'rdflib/src/indexed-formula'>;
}
declare module 'rdflib/src/jsonparser.js' {
  declare module.exports: $Exports<'rdflib/src/jsonparser'>;
}
declare module 'rdflib/src/literal.js' {
  declare module.exports: $Exports<'rdflib/src/literal'>;
}
declare module 'rdflib/src/log.js' {
  declare module.exports: $Exports<'rdflib/src/log'>;
}
declare module 'rdflib/src/n3parser.js' {
  declare module.exports: $Exports<'rdflib/src/n3parser'>;
}
declare module 'rdflib/src/named-node.js' {
  declare module.exports: $Exports<'rdflib/src/named-node'>;
}
declare module 'rdflib/src/namespace.js' {
  declare module.exports: $Exports<'rdflib/src/namespace'>;
}
declare module 'rdflib/src/node.js' {
  declare module.exports: $Exports<'rdflib/src/node'>;
}
declare module 'rdflib/src/parse.js' {
  declare module.exports: $Exports<'rdflib/src/parse'>;
}
declare module 'rdflib/src/patch-parser.js' {
  declare module.exports: $Exports<'rdflib/src/patch-parser'>;
}
declare module 'rdflib/src/query-to-sparql.js' {
  declare module.exports: $Exports<'rdflib/src/query-to-sparql'>;
}
declare module 'rdflib/src/query.js' {
  declare module.exports: $Exports<'rdflib/src/query'>;
}
declare module 'rdflib/src/rdfaparser.js' {
  declare module.exports: $Exports<'rdflib/src/rdfaparser'>;
}
declare module 'rdflib/src/rdfxmlparser.js' {
  declare module.exports: $Exports<'rdflib/src/rdfxmlparser'>;
}
declare module 'rdflib/src/serialize.js' {
  declare module.exports: $Exports<'rdflib/src/serialize'>;
}
declare module 'rdflib/src/serializer.js' {
  declare module.exports: $Exports<'rdflib/src/serializer'>;
}
declare module 'rdflib/src/sparql-to-query.js' {
  declare module.exports: $Exports<'rdflib/src/sparql-to-query'>;
}
declare module 'rdflib/src/statement.js' {
  declare module.exports: $Exports<'rdflib/src/statement'>;
}
declare module 'rdflib/src/update-manager.js' {
  declare module.exports: $Exports<'rdflib/src/update-manager'>;
}
declare module 'rdflib/src/updates-via.js' {
  declare module.exports: $Exports<'rdflib/src/updates-via'>;
}
declare module 'rdflib/src/uri.js' {
  declare module.exports: $Exports<'rdflib/src/uri'>;
}
declare module 'rdflib/src/util.js' {
  declare module.exports: $Exports<'rdflib/src/util'>;
}
declare module 'rdflib/src/variable.js' {
  declare module.exports: $Exports<'rdflib/src/variable'>;
}
declare module 'rdflib/src/xsd.js' {
  declare module.exports: $Exports<'rdflib/src/xsd'>;
}
