// flow-typed signature: 2141c60057623e7603c95f3d1043d03e
// flow-typed version: <<STUB>>/re-base_v^2.7.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 're-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-base/dist/bundle' {
  declare module.exports: any;
}

declare module 're-base/examples/chatapp/src/App' {
  declare module.exports: any;
}

declare module 're-base/examples/chatapp/src/components/Container' {
  declare module.exports: any;
}

declare module 're-base/examples/chatapp/src/components/Message' {
  declare module.exports: any;
}

declare module 're-base/examples/chatapp/src/components/NewChat' {
  declare module.exports: any;
}

declare module 're-base/examples/chatapp/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/App' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Github/Repos' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Github/UserProfile' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Home' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Main' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Notes/AddNote' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Notes/Notes' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Notes/NotesList' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/Profile' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/components/SearchGithub' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/config/routes' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/app/utils/helpers' {
  declare module.exports: any;
}

declare module 're-base/examples/github-notetaker/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/todolist - syncState/app/AddItem' {
  declare module.exports: any;
}

declare module 're-base/examples/todolist - syncState/app/App' {
  declare module.exports: any;
}

declare module 're-base/examples/todolist - syncState/app/List' {
  declare module.exports: any;
}

declare module 're-base/examples/todolist - syncState/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/authWithCustomToken' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/authWithOAuthPopup' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/authWithOAuthRedirect' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/authWithOAuthToken' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/authWithPassword' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/getAuth' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/getAuthProvider' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/getOAuthRedirectResult' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/onAuth' {
  declare module.exports: any;
}

declare module 're-base/src/lib/auth/unauth' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/bind' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/fetch' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/post' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/push' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/remove' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/removeBinding' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/reset' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/sync' {
  declare module.exports: any;
}

declare module 're-base/src/lib/database/update' {
  declare module.exports: any;
}

declare module 're-base/src/lib/user/createUser' {
  declare module.exports: any;
}

declare module 're-base/src/lib/user/resetPassword' {
  declare module.exports: any;
}

declare module 're-base/src/lib/utils' {
  declare module.exports: any;
}

declare module 're-base/src/lib/validators' {
  declare module.exports: any;
}

declare module 're-base/src/rebase' {
  declare module.exports: any;
}

declare module 're-base/tests/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify' {
  declare module.exports: any;
}

declare module 're-base/tests/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/config' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyArrayOfObjects' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyArrData' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyNestedObjData' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyObjData' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyUsers' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/invalidEndpoints' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/invalidOptions' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/nestedObjArrResult' {
  declare module.exports: any;
}

declare module 're-base/tests/karma.conf' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/auth.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/bindToState.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/createClass.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/delete.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/fetch.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/listenTo.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/post.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/push.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/remove.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/removeBinding.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/reset.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/serverinfo.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/services.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/syncState.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/update.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/user.spec' {
  declare module.exports: any;
}

declare module 're-base/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-base/dist/bundle.js' {
  declare module.exports: $Exports<'re-base/dist/bundle'>;
}
declare module 're-base/examples/chatapp/src/App.js' {
  declare module.exports: $Exports<'re-base/examples/chatapp/src/App'>;
}
declare module 're-base/examples/chatapp/src/components/Container.js' {
  declare module.exports: $Exports<'re-base/examples/chatapp/src/components/Container'>;
}
declare module 're-base/examples/chatapp/src/components/Message.js' {
  declare module.exports: $Exports<'re-base/examples/chatapp/src/components/Message'>;
}
declare module 're-base/examples/chatapp/src/components/NewChat.js' {
  declare module.exports: $Exports<'re-base/examples/chatapp/src/components/NewChat'>;
}
declare module 're-base/examples/chatapp/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/chatapp/webpack.config'>;
}
declare module 're-base/examples/github-notetaker/app/App.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/App'>;
}
declare module 're-base/examples/github-notetaker/app/components/Github/Repos.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Github/Repos'>;
}
declare module 're-base/examples/github-notetaker/app/components/Github/UserProfile.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Github/UserProfile'>;
}
declare module 're-base/examples/github-notetaker/app/components/Home.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Home'>;
}
declare module 're-base/examples/github-notetaker/app/components/Main.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Main'>;
}
declare module 're-base/examples/github-notetaker/app/components/Notes/AddNote.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Notes/AddNote'>;
}
declare module 're-base/examples/github-notetaker/app/components/Notes/Notes.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Notes/Notes'>;
}
declare module 're-base/examples/github-notetaker/app/components/Notes/NotesList.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Notes/NotesList'>;
}
declare module 're-base/examples/github-notetaker/app/components/Profile.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/Profile'>;
}
declare module 're-base/examples/github-notetaker/app/components/SearchGithub.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/components/SearchGithub'>;
}
declare module 're-base/examples/github-notetaker/app/config/routes.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/config/routes'>;
}
declare module 're-base/examples/github-notetaker/app/utils/helpers.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/app/utils/helpers'>;
}
declare module 're-base/examples/github-notetaker/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/github-notetaker/webpack.config'>;
}
declare module 're-base/examples/todolist - syncState/app/AddItem.js' {
  declare module.exports: $Exports<'re-base/examples/todolist - syncState/app/AddItem'>;
}
declare module 're-base/examples/todolist - syncState/app/App.js' {
  declare module.exports: $Exports<'re-base/examples/todolist - syncState/app/App'>;
}
declare module 're-base/examples/todolist - syncState/app/List.js' {
  declare module.exports: $Exports<'re-base/examples/todolist - syncState/app/List'>;
}
declare module 're-base/examples/todolist - syncState/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/todolist - syncState/webpack.config'>;
}
declare module 're-base/index' {
  declare module.exports: $Exports<'re-base'>;
}
declare module 're-base/index.js' {
  declare module.exports: $Exports<'re-base'>;
}
declare module 're-base/src/lib/auth/authWithCustomToken.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/authWithCustomToken'>;
}
declare module 're-base/src/lib/auth/authWithOAuthPopup.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/authWithOAuthPopup'>;
}
declare module 're-base/src/lib/auth/authWithOAuthRedirect.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/authWithOAuthRedirect'>;
}
declare module 're-base/src/lib/auth/authWithOAuthToken.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/authWithOAuthToken'>;
}
declare module 're-base/src/lib/auth/authWithPassword.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/authWithPassword'>;
}
declare module 're-base/src/lib/auth/getAuth.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/getAuth'>;
}
declare module 're-base/src/lib/auth/getAuthProvider.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/getAuthProvider'>;
}
declare module 're-base/src/lib/auth/getOAuthRedirectResult.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/getOAuthRedirectResult'>;
}
declare module 're-base/src/lib/auth/onAuth.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/onAuth'>;
}
declare module 're-base/src/lib/auth/unauth.js' {
  declare module.exports: $Exports<'re-base/src/lib/auth/unauth'>;
}
declare module 're-base/src/lib/database/bind.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/bind'>;
}
declare module 're-base/src/lib/database/fetch.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/fetch'>;
}
declare module 're-base/src/lib/database/post.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/post'>;
}
declare module 're-base/src/lib/database/push.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/push'>;
}
declare module 're-base/src/lib/database/remove.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/remove'>;
}
declare module 're-base/src/lib/database/removeBinding.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/removeBinding'>;
}
declare module 're-base/src/lib/database/reset.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/reset'>;
}
declare module 're-base/src/lib/database/sync.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/sync'>;
}
declare module 're-base/src/lib/database/update.js' {
  declare module.exports: $Exports<'re-base/src/lib/database/update'>;
}
declare module 're-base/src/lib/user/createUser.js' {
  declare module.exports: $Exports<'re-base/src/lib/user/createUser'>;
}
declare module 're-base/src/lib/user/resetPassword.js' {
  declare module.exports: $Exports<'re-base/src/lib/user/resetPassword'>;
}
declare module 're-base/src/lib/utils.js' {
  declare module.exports: $Exports<'re-base/src/lib/utils'>;
}
declare module 're-base/src/lib/validators.js' {
  declare module.exports: $Exports<'re-base/src/lib/validators'>;
}
declare module 're-base/src/rebase.js' {
  declare module.exports: $Exports<'re-base/src/rebase'>;
}
declare module 're-base/tests/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify.js' {
  declare module.exports: $Exports<'re-base/tests/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify'>;
}
declare module 're-base/tests/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter.js' {
  declare module.exports: $Exports<'re-base/tests/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter'>;
}
declare module 're-base/tests/fixtures/config.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/config'>;
}
declare module 're-base/tests/fixtures/dummyArrayOfObjects.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyArrayOfObjects'>;
}
declare module 're-base/tests/fixtures/dummyArrData.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyArrData'>;
}
declare module 're-base/tests/fixtures/dummyNestedObjData.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyNestedObjData'>;
}
declare module 're-base/tests/fixtures/dummyObjData.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyObjData'>;
}
declare module 're-base/tests/fixtures/dummyUsers.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyUsers'>;
}
declare module 're-base/tests/fixtures/invalidEndpoints.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/invalidEndpoints'>;
}
declare module 're-base/tests/fixtures/invalidOptions.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/invalidOptions'>;
}
declare module 're-base/tests/fixtures/nestedObjArrResult.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/nestedObjArrResult'>;
}
declare module 're-base/tests/karma.conf.js' {
  declare module.exports: $Exports<'re-base/tests/karma.conf'>;
}
declare module 're-base/tests/specs/auth.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/auth.spec'>;
}
declare module 're-base/tests/specs/bindToState.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/bindToState.spec'>;
}
declare module 're-base/tests/specs/createClass.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/createClass.spec'>;
}
declare module 're-base/tests/specs/delete.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/delete.spec'>;
}
declare module 're-base/tests/specs/fetch.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/fetch.spec'>;
}
declare module 're-base/tests/specs/listenTo.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/listenTo.spec'>;
}
declare module 're-base/tests/specs/post.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/post.spec'>;
}
declare module 're-base/tests/specs/push.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/push.spec'>;
}
declare module 're-base/tests/specs/remove.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/remove.spec'>;
}
declare module 're-base/tests/specs/removeBinding.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/removeBinding.spec'>;
}
declare module 're-base/tests/specs/reset.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/reset.spec'>;
}
declare module 're-base/tests/specs/serverinfo.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/serverinfo.spec'>;
}
declare module 're-base/tests/specs/services.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/services.spec'>;
}
declare module 're-base/tests/specs/syncState.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/syncState.spec'>;
}
declare module 're-base/tests/specs/update.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/update.spec'>;
}
declare module 're-base/tests/specs/user.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/user.spec'>;
}
declare module 're-base/webpack.config.js' {
  declare module.exports: $Exports<'re-base/webpack.config'>;
}
