// flow-typed signature: 26291cd6941b3b81a5f280694ba3a32f
// flow-typed version: <<STUB>>/react-mfb_v^0.4.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mfb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mfb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mfb/build/child-button' {
  declare module.exports: any;
}

declare module 'react-mfb/build/main-button' {
  declare module.exports: any;
}

declare module 'react-mfb/build/menu' {
  declare module.exports: any;
}

declare module 'react-mfb/build/utils/children-validator' {
  declare module.exports: any;
}

declare module 'react-mfb/build/utils/get-children' {
  declare module.exports: any;
}

declare module 'react-mfb/build/utils/get-classes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mfb/build/child-button.js' {
  declare module.exports: $Exports<'react-mfb/build/child-button'>;
}
declare module 'react-mfb/build/main-button.js' {
  declare module.exports: $Exports<'react-mfb/build/main-button'>;
}
declare module 'react-mfb/build/menu.js' {
  declare module.exports: $Exports<'react-mfb/build/menu'>;
}
declare module 'react-mfb/build/utils/children-validator.js' {
  declare module.exports: $Exports<'react-mfb/build/utils/children-validator'>;
}
declare module 'react-mfb/build/utils/get-children.js' {
  declare module.exports: $Exports<'react-mfb/build/utils/get-children'>;
}
declare module 'react-mfb/build/utils/get-classes.js' {
  declare module.exports: $Exports<'react-mfb/build/utils/get-classes'>;
}
declare module 'react-mfb/index' {
  declare module.exports: $Exports<'react-mfb'>;
}
declare module 'react-mfb/index.js' {
  declare module.exports: $Exports<'react-mfb'>;
}
