// flow-typed signature: 99fedd3aa63235ec86b27ccbff510788
// flow-typed version: <<STUB>>/react-fab_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fab/dist/components/Fab' {
  declare module.exports: any;
}

declare module 'react-fab/dist/components/FabAction' {
  declare module.exports: any;
}

declare module 'react-fab/dist/components/FabActions' {
  declare module.exports: any;
}

declare module 'react-fab/dist/components/FabButton' {
  declare module.exports: any;
}

declare module 'react-fab/dist/index' {
  declare module.exports: any;
}

declare module 'react-fab/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/Fab' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/Fab.test' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/FabAction' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/FabAction.test' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/FabActions' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/FabActions.test' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/FabButton' {
  declare module.exports: any;
}

declare module 'react-fab/src/components/FabButton.test' {
  declare module.exports: any;
}

declare module 'react-fab/src/index' {
  declare module.exports: any;
}

declare module 'react-fab/test-boot' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fab/dist/components/Fab.js' {
  declare module.exports: $Exports<'react-fab/dist/components/Fab'>;
}
declare module 'react-fab/dist/components/FabAction.js' {
  declare module.exports: $Exports<'react-fab/dist/components/FabAction'>;
}
declare module 'react-fab/dist/components/FabActions.js' {
  declare module.exports: $Exports<'react-fab/dist/components/FabActions'>;
}
declare module 'react-fab/dist/components/FabButton.js' {
  declare module.exports: $Exports<'react-fab/dist/components/FabButton'>;
}
declare module 'react-fab/dist/index.js' {
  declare module.exports: $Exports<'react-fab/dist/index'>;
}
declare module 'react-fab/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-fab/gulpfile.babel'>;
}
declare module 'react-fab/src/components/Fab.js' {
  declare module.exports: $Exports<'react-fab/src/components/Fab'>;
}
declare module 'react-fab/src/components/Fab.test.js' {
  declare module.exports: $Exports<'react-fab/src/components/Fab.test'>;
}
declare module 'react-fab/src/components/FabAction.js' {
  declare module.exports: $Exports<'react-fab/src/components/FabAction'>;
}
declare module 'react-fab/src/components/FabAction.test.js' {
  declare module.exports: $Exports<'react-fab/src/components/FabAction.test'>;
}
declare module 'react-fab/src/components/FabActions.js' {
  declare module.exports: $Exports<'react-fab/src/components/FabActions'>;
}
declare module 'react-fab/src/components/FabActions.test.js' {
  declare module.exports: $Exports<'react-fab/src/components/FabActions.test'>;
}
declare module 'react-fab/src/components/FabButton.js' {
  declare module.exports: $Exports<'react-fab/src/components/FabButton'>;
}
declare module 'react-fab/src/components/FabButton.test.js' {
  declare module.exports: $Exports<'react-fab/src/components/FabButton.test'>;
}
declare module 'react-fab/src/index.js' {
  declare module.exports: $Exports<'react-fab/src/index'>;
}
declare module 'react-fab/test-boot.js' {
  declare module.exports: $Exports<'react-fab/test-boot'>;
}
