// flow-typed signature: e141b6e52d6b1e4b54884705a11976f1
// flow-typed version: <<STUB>>/react-svg-buttons_v^0.3.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-buttons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-buttons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-buttons/lib/components/buttons/CloseButton' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/components/buttons/NavButton' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/components/buttons/PlayButton' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/components/buttons/PlusButton' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/components/HoverMorphIcon' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/components/MorphIcon' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/arrow-down' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/arrow-left' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/arrow-right' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/arrow-up' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/ban' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/bars' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/check' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/code' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/cross-sparks' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/cross' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/ffwd' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/fwd' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/hashtag' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/home' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/inbox' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/index' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/pause-circle' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/pause-sparks' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/pause' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/play-circle' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/play-sparks' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/play' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/plus-sparks' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/plus' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/icon-types/thunderbolt' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/index' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/lib/clamp' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/lib/omit' {
  declare module.exports: any;
}

declare module 'react-svg-buttons/lib/lib/pathHelper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-buttons/lib/components/buttons/CloseButton.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/components/buttons/CloseButton'>;
}
declare module 'react-svg-buttons/lib/components/buttons/NavButton.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/components/buttons/NavButton'>;
}
declare module 'react-svg-buttons/lib/components/buttons/PlayButton.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/components/buttons/PlayButton'>;
}
declare module 'react-svg-buttons/lib/components/buttons/PlusButton.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/components/buttons/PlusButton'>;
}
declare module 'react-svg-buttons/lib/components/HoverMorphIcon.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/components/HoverMorphIcon'>;
}
declare module 'react-svg-buttons/lib/components/MorphIcon.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/components/MorphIcon'>;
}
declare module 'react-svg-buttons/lib/icon-types/arrow-down.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/arrow-down'>;
}
declare module 'react-svg-buttons/lib/icon-types/arrow-left.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/arrow-left'>;
}
declare module 'react-svg-buttons/lib/icon-types/arrow-right.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/arrow-right'>;
}
declare module 'react-svg-buttons/lib/icon-types/arrow-up.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/arrow-up'>;
}
declare module 'react-svg-buttons/lib/icon-types/ban.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/ban'>;
}
declare module 'react-svg-buttons/lib/icon-types/bars.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/bars'>;
}
declare module 'react-svg-buttons/lib/icon-types/check.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/check'>;
}
declare module 'react-svg-buttons/lib/icon-types/code.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/code'>;
}
declare module 'react-svg-buttons/lib/icon-types/cross-sparks.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/cross-sparks'>;
}
declare module 'react-svg-buttons/lib/icon-types/cross.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/cross'>;
}
declare module 'react-svg-buttons/lib/icon-types/ffwd.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/ffwd'>;
}
declare module 'react-svg-buttons/lib/icon-types/fwd.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/fwd'>;
}
declare module 'react-svg-buttons/lib/icon-types/hashtag.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/hashtag'>;
}
declare module 'react-svg-buttons/lib/icon-types/home.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/home'>;
}
declare module 'react-svg-buttons/lib/icon-types/inbox.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/inbox'>;
}
declare module 'react-svg-buttons/lib/icon-types/index.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/index'>;
}
declare module 'react-svg-buttons/lib/icon-types/pause-circle.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/pause-circle'>;
}
declare module 'react-svg-buttons/lib/icon-types/pause-sparks.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/pause-sparks'>;
}
declare module 'react-svg-buttons/lib/icon-types/pause.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/pause'>;
}
declare module 'react-svg-buttons/lib/icon-types/play-circle.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/play-circle'>;
}
declare module 'react-svg-buttons/lib/icon-types/play-sparks.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/play-sparks'>;
}
declare module 'react-svg-buttons/lib/icon-types/play.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/play'>;
}
declare module 'react-svg-buttons/lib/icon-types/plus-sparks.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/plus-sparks'>;
}
declare module 'react-svg-buttons/lib/icon-types/plus.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/plus'>;
}
declare module 'react-svg-buttons/lib/icon-types/thunderbolt.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/icon-types/thunderbolt'>;
}
declare module 'react-svg-buttons/lib/index.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/index'>;
}
declare module 'react-svg-buttons/lib/lib/clamp.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/lib/clamp'>;
}
declare module 'react-svg-buttons/lib/lib/omit.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/lib/omit'>;
}
declare module 'react-svg-buttons/lib/lib/pathHelper.js' {
  declare module.exports: $Exports<'react-svg-buttons/lib/lib/pathHelper'>;
}
