// flow-typed signature: f5626430234bad7a92815356f3b1c9c4
// flow-typed version: <<STUB>>/react-notifications_v^1.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-notifications/dist/react-notifications' {
  declare module.exports: any;
}

declare module 'react-notifications/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/index' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/Notification' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/NotificationContainer' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/NotificationManager' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/Notifications' {
  declare module.exports: any;
}

declare module 'react-notifications/src/index' {
  declare module.exports: any;
}

declare module 'react-notifications/src/Notification' {
  declare module.exports: any;
}

declare module 'react-notifications/src/NotificationContainer' {
  declare module.exports: any;
}

declare module 'react-notifications/src/NotificationManager' {
  declare module.exports: any;
}

declare module 'react-notifications/src/Notifications' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/example' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/lib' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/lib/babel' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/lib/clean' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/lib/copy' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/lib/lint' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/lib/sass' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/build/lib/umd' {
  declare module.exports: any;
}

declare module 'react-notifications/tasks/start' {
  declare module.exports: any;
}

declare module 'react-notifications/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-notifications/dist/react-notifications.js' {
  declare module.exports: $Exports<'react-notifications/dist/react-notifications'>;
}
declare module 'react-notifications/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-notifications/gulpfile.babel'>;
}
declare module 'react-notifications/lib/index.js' {
  declare module.exports: $Exports<'react-notifications/lib/index'>;
}
declare module 'react-notifications/lib/Notification.js' {
  declare module.exports: $Exports<'react-notifications/lib/Notification'>;
}
declare module 'react-notifications/lib/NotificationContainer.js' {
  declare module.exports: $Exports<'react-notifications/lib/NotificationContainer'>;
}
declare module 'react-notifications/lib/NotificationManager.js' {
  declare module.exports: $Exports<'react-notifications/lib/NotificationManager'>;
}
declare module 'react-notifications/lib/Notifications.js' {
  declare module.exports: $Exports<'react-notifications/lib/Notifications'>;
}
declare module 'react-notifications/src/index.js' {
  declare module.exports: $Exports<'react-notifications/src/index'>;
}
declare module 'react-notifications/src/Notification.js' {
  declare module.exports: $Exports<'react-notifications/src/Notification'>;
}
declare module 'react-notifications/src/NotificationContainer.js' {
  declare module.exports: $Exports<'react-notifications/src/NotificationContainer'>;
}
declare module 'react-notifications/src/NotificationManager.js' {
  declare module.exports: $Exports<'react-notifications/src/NotificationManager'>;
}
declare module 'react-notifications/src/Notifications.js' {
  declare module.exports: $Exports<'react-notifications/src/Notifications'>;
}
declare module 'react-notifications/tasks/build.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build'>;
}
declare module 'react-notifications/tasks/build/example.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/example'>;
}
declare module 'react-notifications/tasks/build/lib.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/lib'>;
}
declare module 'react-notifications/tasks/build/lib/babel.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/lib/babel'>;
}
declare module 'react-notifications/tasks/build/lib/clean.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/lib/clean'>;
}
declare module 'react-notifications/tasks/build/lib/copy.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/lib/copy'>;
}
declare module 'react-notifications/tasks/build/lib/lint.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/lib/lint'>;
}
declare module 'react-notifications/tasks/build/lib/sass.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/lib/sass'>;
}
declare module 'react-notifications/tasks/build/lib/umd.js' {
  declare module.exports: $Exports<'react-notifications/tasks/build/lib/umd'>;
}
declare module 'react-notifications/tasks/start.js' {
  declare module.exports: $Exports<'react-notifications/tasks/start'>;
}
declare module 'react-notifications/webpack.config.js' {
  declare module.exports: $Exports<'react-notifications/webpack.config'>;
}
