// flow-typed signature: 9d8bd2845af50e39efe3ecbec7274607
// flow-typed version: <<STUB>>/react-router5_v^4.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router5/dist/commonjs/BaseLink' {
  declare module.exports: any;
}

declare module 'react-router5/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-router5/dist/commonjs/routeNode' {
  declare module.exports: any;
}

declare module 'react-router5/dist/commonjs/RouterProvider' {
  declare module.exports: any;
}

declare module 'react-router5/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-router5/dist/commonjs/withRoute' {
  declare module.exports: any;
}

declare module 'react-router5/dist/es/BaseLink' {
  declare module.exports: any;
}

declare module 'react-router5/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-router5/dist/es/routeNode' {
  declare module.exports: any;
}

declare module 'react-router5/dist/es/RouterProvider' {
  declare module.exports: any;
}

declare module 'react-router5/dist/es/utils' {
  declare module.exports: any;
}

declare module 'react-router5/dist/es/withRoute' {
  declare module.exports: any;
}

declare module 'react-router5/dist/umd/react-router5' {
  declare module.exports: any;
}

declare module 'react-router5/modules/BaseLink' {
  declare module.exports: any;
}

declare module 'react-router5/modules/index' {
  declare module.exports: any;
}

declare module 'react-router5/modules/routeNode' {
  declare module.exports: any;
}

declare module 'react-router5/modules/RouterProvider' {
  declare module.exports: any;
}

declare module 'react-router5/modules/utils' {
  declare module.exports: any;
}

declare module 'react-router5/modules/withRoute' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router5/dist/commonjs/BaseLink.js' {
  declare module.exports: $Exports<'react-router5/dist/commonjs/BaseLink'>;
}
declare module 'react-router5/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-router5/dist/commonjs/index'>;
}
declare module 'react-router5/dist/commonjs/routeNode.js' {
  declare module.exports: $Exports<'react-router5/dist/commonjs/routeNode'>;
}
declare module 'react-router5/dist/commonjs/RouterProvider.js' {
  declare module.exports: $Exports<'react-router5/dist/commonjs/RouterProvider'>;
}
declare module 'react-router5/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'react-router5/dist/commonjs/utils'>;
}
declare module 'react-router5/dist/commonjs/withRoute.js' {
  declare module.exports: $Exports<'react-router5/dist/commonjs/withRoute'>;
}
declare module 'react-router5/dist/es/BaseLink.js' {
  declare module.exports: $Exports<'react-router5/dist/es/BaseLink'>;
}
declare module 'react-router5/dist/es/index.js' {
  declare module.exports: $Exports<'react-router5/dist/es/index'>;
}
declare module 'react-router5/dist/es/routeNode.js' {
  declare module.exports: $Exports<'react-router5/dist/es/routeNode'>;
}
declare module 'react-router5/dist/es/RouterProvider.js' {
  declare module.exports: $Exports<'react-router5/dist/es/RouterProvider'>;
}
declare module 'react-router5/dist/es/utils.js' {
  declare module.exports: $Exports<'react-router5/dist/es/utils'>;
}
declare module 'react-router5/dist/es/withRoute.js' {
  declare module.exports: $Exports<'react-router5/dist/es/withRoute'>;
}
declare module 'react-router5/dist/umd/react-router5.js' {
  declare module.exports: $Exports<'react-router5/dist/umd/react-router5'>;
}
declare module 'react-router5/modules/BaseLink.js' {
  declare module.exports: $Exports<'react-router5/modules/BaseLink'>;
}
declare module 'react-router5/modules/index.js' {
  declare module.exports: $Exports<'react-router5/modules/index'>;
}
declare module 'react-router5/modules/routeNode.js' {
  declare module.exports: $Exports<'react-router5/modules/routeNode'>;
}
declare module 'react-router5/modules/RouterProvider.js' {
  declare module.exports: $Exports<'react-router5/modules/RouterProvider'>;
}
declare module 'react-router5/modules/utils.js' {
  declare module.exports: $Exports<'react-router5/modules/utils'>;
}
declare module 'react-router5/modules/withRoute.js' {
  declare module.exports: $Exports<'react-router5/modules/withRoute'>;
}
