// flow-typed signature: fefea9ad05a48f601e5019828973ec18
// flow-typed version: <<STUB>>/redux-router5_v^4.2.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-router5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-router5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-router5/dist/es/immutable/reducer' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/es/index' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/es/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/es/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/es/lib/reduxPlugin' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/es/lib/routeNodeSelector' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/es/lib/router5Middleware' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/es/lib/router5Reducer' {
  declare module.exports: any;
}

declare module 'redux-router5/dist/umd/redux-router5' {
  declare module.exports: any;
}

declare module 'redux-router5/immutable/reducer' {
  declare module.exports: any;
}

declare module 'redux-router5/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-router5/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-router5/lib/reduxPlugin' {
  declare module.exports: any;
}

declare module 'redux-router5/lib/routeNodeSelector' {
  declare module.exports: any;
}

declare module 'redux-router5/lib/router5Middleware' {
  declare module.exports: any;
}

declare module 'redux-router5/lib/router5Reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-router5/dist/es/immutable/reducer.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/immutable/reducer'>;
}
declare module 'redux-router5/dist/es/index.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/index'>;
}
declare module 'redux-router5/dist/es/lib/actions.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/lib/actions'>;
}
declare module 'redux-router5/dist/es/lib/actionTypes.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/lib/actionTypes'>;
}
declare module 'redux-router5/dist/es/lib/reduxPlugin.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/lib/reduxPlugin'>;
}
declare module 'redux-router5/dist/es/lib/routeNodeSelector.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/lib/routeNodeSelector'>;
}
declare module 'redux-router5/dist/es/lib/router5Middleware.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/lib/router5Middleware'>;
}
declare module 'redux-router5/dist/es/lib/router5Reducer.js' {
  declare module.exports: $Exports<'redux-router5/dist/es/lib/router5Reducer'>;
}
declare module 'redux-router5/dist/umd/redux-router5.js' {
  declare module.exports: $Exports<'redux-router5/dist/umd/redux-router5'>;
}
declare module 'redux-router5/immutable/reducer.js' {
  declare module.exports: $Exports<'redux-router5/immutable/reducer'>;
}
declare module 'redux-router5/index' {
  declare module.exports: $Exports<'redux-router5'>;
}
declare module 'redux-router5/index.js' {
  declare module.exports: $Exports<'redux-router5'>;
}
declare module 'redux-router5/lib/actions.js' {
  declare module.exports: $Exports<'redux-router5/lib/actions'>;
}
declare module 'redux-router5/lib/actionTypes.js' {
  declare module.exports: $Exports<'redux-router5/lib/actionTypes'>;
}
declare module 'redux-router5/lib/reduxPlugin.js' {
  declare module.exports: $Exports<'redux-router5/lib/reduxPlugin'>;
}
declare module 'redux-router5/lib/routeNodeSelector.js' {
  declare module.exports: $Exports<'redux-router5/lib/routeNodeSelector'>;
}
declare module 'redux-router5/lib/router5Middleware.js' {
  declare module.exports: $Exports<'redux-router5/lib/router5Middleware'>;
}
declare module 'redux-router5/lib/router5Reducer.js' {
  declare module.exports: $Exports<'redux-router5/lib/router5Reducer'>;
}
