// flow-typed signature: e7f80afd36bd8b88b1e264f57c3f9823
// flow-typed version: <<STUB>>/router5_v^4.5.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'router5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'router5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'router5/constants' {
  declare module.exports: any;
}

declare module 'router5/core/clone' {
  declare module.exports: any;
}

declare module 'router5/core/middleware' {
  declare module.exports: any;
}

declare module 'router5/core/navigation' {
  declare module.exports: any;
}

declare module 'router5/core/plugins' {
  declare module.exports: any;
}

declare module 'router5/core/route-lifecycle' {
  declare module.exports: any;
}

declare module 'router5/core/router-lifecycle' {
  declare module.exports: any;
}

declare module 'router5/core/utils' {
  declare module.exports: any;
}

declare module 'router5/create-router' {
  declare module.exports: any;
}

declare module 'router5/dist/es/constants' {
  declare module.exports: any;
}

declare module 'router5/dist/es/core/clone' {
  declare module.exports: any;
}

declare module 'router5/dist/es/core/middleware' {
  declare module.exports: any;
}

declare module 'router5/dist/es/core/navigation' {
  declare module.exports: any;
}

declare module 'router5/dist/es/core/plugins' {
  declare module.exports: any;
}

declare module 'router5/dist/es/core/route-lifecycle' {
  declare module.exports: any;
}

declare module 'router5/dist/es/core/router-lifecycle' {
  declare module.exports: any;
}

declare module 'router5/dist/es/core/utils' {
  declare module.exports: any;
}

declare module 'router5/dist/es/create-router' {
  declare module.exports: any;
}

declare module 'router5/dist/es/index' {
  declare module.exports: any;
}

declare module 'router5/dist/es/plugins/browser/browser' {
  declare module.exports: any;
}

declare module 'router5/dist/es/plugins/browser/index' {
  declare module.exports: any;
}

declare module 'router5/dist/es/plugins/browser/utils' {
  declare module.exports: any;
}

declare module 'router5/dist/es/plugins/listeners/index' {
  declare module.exports: any;
}

declare module 'router5/dist/es/plugins/logger/index' {
  declare module.exports: any;
}

declare module 'router5/dist/es/plugins/persistentParams/index' {
  declare module.exports: any;
}

declare module 'router5/dist/es/transition/index' {
  declare module.exports: any;
}

declare module 'router5/dist/es/transition/resolve' {
  declare module.exports: any;
}

declare module 'router5/dist/umd/router5' {
  declare module.exports: any;
}

declare module 'router5/dist/umd/router5.min' {
  declare module.exports: any;
}

declare module 'router5/dist/umd/router5BrowserPlugin' {
  declare module.exports: any;
}

declare module 'router5/dist/umd/router5ListenersPlugin' {
  declare module.exports: any;
}

declare module 'router5/dist/umd/router5PersistentParamsPlugin' {
  declare module.exports: any;
}

declare module 'router5/plugins/browser/browser' {
  declare module.exports: any;
}

declare module 'router5/plugins/browser/index' {
  declare module.exports: any;
}

declare module 'router5/plugins/browser/utils' {
  declare module.exports: any;
}

declare module 'router5/plugins/listeners/index' {
  declare module.exports: any;
}

declare module 'router5/plugins/logger/index' {
  declare module.exports: any;
}

declare module 'router5/plugins/persistentParams/index' {
  declare module.exports: any;
}

declare module 'router5/transition/index' {
  declare module.exports: any;
}

declare module 'router5/transition/resolve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'router5/constants.js' {
  declare module.exports: $Exports<'router5/constants'>;
}
declare module 'router5/core/clone.js' {
  declare module.exports: $Exports<'router5/core/clone'>;
}
declare module 'router5/core/middleware.js' {
  declare module.exports: $Exports<'router5/core/middleware'>;
}
declare module 'router5/core/navigation.js' {
  declare module.exports: $Exports<'router5/core/navigation'>;
}
declare module 'router5/core/plugins.js' {
  declare module.exports: $Exports<'router5/core/plugins'>;
}
declare module 'router5/core/route-lifecycle.js' {
  declare module.exports: $Exports<'router5/core/route-lifecycle'>;
}
declare module 'router5/core/router-lifecycle.js' {
  declare module.exports: $Exports<'router5/core/router-lifecycle'>;
}
declare module 'router5/core/utils.js' {
  declare module.exports: $Exports<'router5/core/utils'>;
}
declare module 'router5/create-router.js' {
  declare module.exports: $Exports<'router5/create-router'>;
}
declare module 'router5/dist/es/constants.js' {
  declare module.exports: $Exports<'router5/dist/es/constants'>;
}
declare module 'router5/dist/es/core/clone.js' {
  declare module.exports: $Exports<'router5/dist/es/core/clone'>;
}
declare module 'router5/dist/es/core/middleware.js' {
  declare module.exports: $Exports<'router5/dist/es/core/middleware'>;
}
declare module 'router5/dist/es/core/navigation.js' {
  declare module.exports: $Exports<'router5/dist/es/core/navigation'>;
}
declare module 'router5/dist/es/core/plugins.js' {
  declare module.exports: $Exports<'router5/dist/es/core/plugins'>;
}
declare module 'router5/dist/es/core/route-lifecycle.js' {
  declare module.exports: $Exports<'router5/dist/es/core/route-lifecycle'>;
}
declare module 'router5/dist/es/core/router-lifecycle.js' {
  declare module.exports: $Exports<'router5/dist/es/core/router-lifecycle'>;
}
declare module 'router5/dist/es/core/utils.js' {
  declare module.exports: $Exports<'router5/dist/es/core/utils'>;
}
declare module 'router5/dist/es/create-router.js' {
  declare module.exports: $Exports<'router5/dist/es/create-router'>;
}
declare module 'router5/dist/es/index.js' {
  declare module.exports: $Exports<'router5/dist/es/index'>;
}
declare module 'router5/dist/es/plugins/browser/browser.js' {
  declare module.exports: $Exports<'router5/dist/es/plugins/browser/browser'>;
}
declare module 'router5/dist/es/plugins/browser/index.js' {
  declare module.exports: $Exports<'router5/dist/es/plugins/browser/index'>;
}
declare module 'router5/dist/es/plugins/browser/utils.js' {
  declare module.exports: $Exports<'router5/dist/es/plugins/browser/utils'>;
}
declare module 'router5/dist/es/plugins/listeners/index.js' {
  declare module.exports: $Exports<'router5/dist/es/plugins/listeners/index'>;
}
declare module 'router5/dist/es/plugins/logger/index.js' {
  declare module.exports: $Exports<'router5/dist/es/plugins/logger/index'>;
}
declare module 'router5/dist/es/plugins/persistentParams/index.js' {
  declare module.exports: $Exports<'router5/dist/es/plugins/persistentParams/index'>;
}
declare module 'router5/dist/es/transition/index.js' {
  declare module.exports: $Exports<'router5/dist/es/transition/index'>;
}
declare module 'router5/dist/es/transition/resolve.js' {
  declare module.exports: $Exports<'router5/dist/es/transition/resolve'>;
}
declare module 'router5/dist/umd/router5.js' {
  declare module.exports: $Exports<'router5/dist/umd/router5'>;
}
declare module 'router5/dist/umd/router5.min.js' {
  declare module.exports: $Exports<'router5/dist/umd/router5.min'>;
}
declare module 'router5/dist/umd/router5BrowserPlugin.js' {
  declare module.exports: $Exports<'router5/dist/umd/router5BrowserPlugin'>;
}
declare module 'router5/dist/umd/router5ListenersPlugin.js' {
  declare module.exports: $Exports<'router5/dist/umd/router5ListenersPlugin'>;
}
declare module 'router5/dist/umd/router5PersistentParamsPlugin.js' {
  declare module.exports: $Exports<'router5/dist/umd/router5PersistentParamsPlugin'>;
}
declare module 'router5/index' {
  declare module.exports: $Exports<'router5'>;
}
declare module 'router5/index.js' {
  declare module.exports: $Exports<'router5'>;
}
declare module 'router5/plugins/browser/browser.js' {
  declare module.exports: $Exports<'router5/plugins/browser/browser'>;
}
declare module 'router5/plugins/browser/index.js' {
  declare module.exports: $Exports<'router5/plugins/browser/index'>;
}
declare module 'router5/plugins/browser/utils.js' {
  declare module.exports: $Exports<'router5/plugins/browser/utils'>;
}
declare module 'router5/plugins/listeners/index.js' {
  declare module.exports: $Exports<'router5/plugins/listeners/index'>;
}
declare module 'router5/plugins/logger/index.js' {
  declare module.exports: $Exports<'router5/plugins/logger/index'>;
}
declare module 'router5/plugins/persistentParams/index.js' {
  declare module.exports: $Exports<'router5/plugins/persistentParams/index'>;
}
declare module 'router5/transition/index.js' {
  declare module.exports: $Exports<'router5/transition/index'>;
}
declare module 'router5/transition/resolve.js' {
  declare module.exports: $Exports<'router5/transition/resolve'>;
}
