// flow-typed signature: 156a3735ae0671cb1d109bcdb6dd3691
// flow-typed version: <<STUB>>/solid-client_v^0.23.7/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'solid-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'solid-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'solid-client/config' {
  declare module.exports: any;
}

declare module 'solid-client/dist/solid-client-lite.min' {
  declare module.exports: any;
}

declare module 'solid-client/dist/solid-client.min' {
  declare module.exports: any;
}

declare module 'solid-client/lib/app-registry' {
  declare module.exports: any;
}

declare module 'solid-client/lib/identity' {
  declare module.exports: any;
}

declare module 'solid-client/lib/index' {
  declare module.exports: any;
}

declare module 'solid-client/lib/meta' {
  declare module.exports: any;
}

declare module 'solid-client/lib/registry' {
  declare module.exports: any;
}

declare module 'solid-client/lib/solid/app-registration' {
  declare module.exports: any;
}

declare module 'solid-client/lib/solid/index-registration' {
  declare module.exports: any;
}

declare module 'solid-client/lib/solid/profile' {
  declare module.exports: any;
}

declare module 'solid-client/lib/status' {
  declare module.exports: any;
}

declare module 'solid-client/lib/type-registry' {
  declare module.exports: any;
}

declare module 'solid-client/lib/util/graph-util' {
  declare module.exports: any;
}

declare module 'solid-client/lib/util/rdf-parser' {
  declare module.exports: any;
}

declare module 'solid-client/lib/util/web-util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'solid-client/config.js' {
  declare module.exports: $Exports<'solid-client/config'>;
}
declare module 'solid-client/dist/solid-client-lite.min.js' {
  declare module.exports: $Exports<'solid-client/dist/solid-client-lite.min'>;
}
declare module 'solid-client/dist/solid-client.min.js' {
  declare module.exports: $Exports<'solid-client/dist/solid-client.min'>;
}
declare module 'solid-client/lib/app-registry.js' {
  declare module.exports: $Exports<'solid-client/lib/app-registry'>;
}
declare module 'solid-client/lib/identity.js' {
  declare module.exports: $Exports<'solid-client/lib/identity'>;
}
declare module 'solid-client/lib/index.js' {
  declare module.exports: $Exports<'solid-client/lib/index'>;
}
declare module 'solid-client/lib/meta.js' {
  declare module.exports: $Exports<'solid-client/lib/meta'>;
}
declare module 'solid-client/lib/registry.js' {
  declare module.exports: $Exports<'solid-client/lib/registry'>;
}
declare module 'solid-client/lib/solid/app-registration.js' {
  declare module.exports: $Exports<'solid-client/lib/solid/app-registration'>;
}
declare module 'solid-client/lib/solid/index-registration.js' {
  declare module.exports: $Exports<'solid-client/lib/solid/index-registration'>;
}
declare module 'solid-client/lib/solid/profile.js' {
  declare module.exports: $Exports<'solid-client/lib/solid/profile'>;
}
declare module 'solid-client/lib/status.js' {
  declare module.exports: $Exports<'solid-client/lib/status'>;
}
declare module 'solid-client/lib/type-registry.js' {
  declare module.exports: $Exports<'solid-client/lib/type-registry'>;
}
declare module 'solid-client/lib/util/graph-util.js' {
  declare module.exports: $Exports<'solid-client/lib/util/graph-util'>;
}
declare module 'solid-client/lib/util/rdf-parser.js' {
  declare module.exports: $Exports<'solid-client/lib/util/rdf-parser'>;
}
declare module 'solid-client/lib/util/web-util.js' {
  declare module.exports: $Exports<'solid-client/lib/util/web-util'>;
}
