// flow-typed signature: 7df69e3acf9adffadd00fac4ad3045a6
// flow-typed version: <<STUB>>/stampit_v3.1.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stampit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stampit' {

  declare interface StampitDescriptor {
    methods?: Object,
    properties?: Object,
    deepProperties?: Object,
    propertyDescriptors?: Object,
    staticProperties?: Object,
    staticDeepProperties?: Object,
    staticPropertyDescriptors?: Object,
    initializers?: Array<() => any>,
    configuration?: Object,
    deepConfiguration?: Object
  }

  declare export default function stampit(descriptor: StampitDescriptor): stampit


  // declare export methods = methods;
  // exports.properties = properties;
  // exports.refs = properties;
  // exports.props = properties;
  // exports.initializers = initializers;
  // exports.init = initializers;
  // exports.composers = composers;
  // exports.deepProperties = deepProperties;
  // exports.deepProps = deepProperties;
  // exports.staticProperties = staticProperties;
  // exports.statics = staticProperties;
  // exports.staticDeepProperties = staticDeepProperties;
  // exports.deepStatics = staticDeepProperties;
  // exports.configuration = configuration;
  // exports.conf = configuration;
  // exports.deepConfiguration = deepConfiguration;
  // exports.deepConf = deepConfiguration;
  // exports.propertyDescriptors = propertyDescriptors;
  // exports.staticPropertyDescriptors = staticPropertyDescriptors;
  // exports.compose = exportedCompose;
  // exports['default'] = stampit$1;
  // module.exports = exports['default'];
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

declare module 'stampit/compose' {
  declare module.exports: any
;
}

declare module 'stampit/dist/stampit.full' {
  declare module.exports: any
;
}

declare module 'stampit/dist/stampit.umd' {
  declare module.exports: any
;
}

declare module 'stampit/dist/stampit.umd.min' {
  declare module.exports: any
;
}

declare module 'stampit/isComposable' {
  declare module.exports: any
;
}

declare module 'stampit/isStamp' {
  declare module.exports: any
;
}
