// flow-typed signature: 034c3617c0ac4a18fe370b97dda12a57
// flow-typed version: <<STUB>>/stampit_v^3.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stampit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stampit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stampit/advanced-examples/cloneable' {
  declare module.exports: any;
}

declare module 'stampit/advanced-examples/event-emitter' {
  declare module.exports: any;
}

declare module 'stampit/advanced-examples/hacking' {
  declare module.exports: any;
}

declare module 'stampit/advanced-examples/mocking' {
  declare module.exports: any;
}

declare module 'stampit/advanced-examples/prevalidate' {
  declare module.exports: any;
}

declare module 'stampit/advanced-examples/self-aware' {
  declare module.exports: any;
}

declare module 'stampit/compose' {
  declare module.exports: any;
}

declare module 'stampit/dist/stampit.full' {
  declare module.exports: any;
}

declare module 'stampit/dist/stampit.umd' {
  declare module.exports: any;
}

declare module 'stampit/dist/stampit.umd.min' {
  declare module.exports: any;
}

declare module 'stampit/isComposable' {
  declare module.exports: any;
}

declare module 'stampit/isStamp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stampit/advanced-examples/cloneable.js' {
  declare module.exports: $Exports<'stampit/advanced-examples/cloneable'>;
}
declare module 'stampit/advanced-examples/event-emitter.js' {
  declare module.exports: $Exports<'stampit/advanced-examples/event-emitter'>;
}
declare module 'stampit/advanced-examples/hacking.js' {
  declare module.exports: $Exports<'stampit/advanced-examples/hacking'>;
}
declare module 'stampit/advanced-examples/mocking.js' {
  declare module.exports: $Exports<'stampit/advanced-examples/mocking'>;
}
declare module 'stampit/advanced-examples/prevalidate.js' {
  declare module.exports: $Exports<'stampit/advanced-examples/prevalidate'>;
}
declare module 'stampit/advanced-examples/self-aware.js' {
  declare module.exports: $Exports<'stampit/advanced-examples/self-aware'>;
}
declare module 'stampit/compose.js' {
  declare module.exports: $Exports<'stampit/compose'>;
}
declare module 'stampit/dist/stampit.full.js' {
  declare module.exports: $Exports<'stampit/dist/stampit.full'>;
}
declare module 'stampit/dist/stampit.umd.js' {
  declare module.exports: $Exports<'stampit/dist/stampit.umd'>;
}
declare module 'stampit/dist/stampit.umd.min.js' {
  declare module.exports: $Exports<'stampit/dist/stampit.umd.min'>;
}
declare module 'stampit/isComposable.js' {
  declare module.exports: $Exports<'stampit/isComposable'>;
}
declare module 'stampit/isStamp.js' {
  declare module.exports: $Exports<'stampit/isStamp'>;
}
